#!/usr/bin/env bash
# Generate lab.env with random secrets. Refuses to overwrite an existing one,
# because doing so would desynchronise the file from a running cluster: the
# realm's client secret and Harbor's copy of it have to stay equal.
set -euo pipefail
cd "$(dirname "$0")/.."

[ -f lab.env ] && { echo "lab.env already exists - not touching it"; exit 0; }

gen() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32; }

cat > lab.env <<EOF
# Generated by scripts/init-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Gitignored. Losing this file means reinstalling the lab.
LAB_DOMAIN=${LAB_DOMAIN:-192.168.1.200.nip.io}

KEYCLOAK_ADMIN_PASSWORD=$(gen)
KEYCLOAK_DB_PASSWORD=$(gen)

HARBOR_ADMIN_PASSWORD=$(gen)
HARBOR_OIDC_CLIENT_SECRET=$(gen)

LAB_USER_DEV_PASSWORD=$(gen)
LAB_USER_ALICE_PASSWORD=$(gen)
EOF

chmod 600 lab.env 2>/dev/null || true
echo "wrote lab.env"
